server:
  port: ${SERVER_PORT:8088}

spring:
  application:
    name: notification-service

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

sqs:
  notification-queue: ${SQS_NOTIFICATION_QUEUE:}

ses:
  from-email: ${SES_FROM_EMAIL:juanpabloc200437@gmail.com
}